//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolaMundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreasD
    {
        public AreasD()
        {
            this.AreaSubareas = new HashSet<AreaSubareas>();
            this.DepartamentoAreaSet = new HashSet<DepartamentoAreaSet>();
            this.GrupoAreas = new HashSet<GrupoAreas>();
        }
    
        public int Cod { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<AreaSubareas> AreaSubareas { get; set; }
        public virtual ICollection<DepartamentoAreaSet> DepartamentoAreaSet { get; set; }
        public virtual ICollection<GrupoAreas> GrupoAreas { get; set; }
    }
}
