//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolaMundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargosSet
    {
        public CargosSet()
        {
            this.EmpleadosSet = new HashSet<EmpleadosSet>();
        }
    
        public int Cod { get; set; }
        public string nombre { get; set; }
        public int jefe { get; set; }
        public string tipo_de_area { get; set; }
    
        public virtual ICollection<EmpleadosSet> EmpleadosSet { get; set; }
    }
}
