//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolaMundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartamentoSedeSet
    {
        public int IdDepSede { get; set; }
        public int SedeId { get; set; }
        public int departamentoId { get; set; }
    
        public virtual departamentoSet departamentoSet { get; set; }
        public virtual SedeSet SedeSet { get; set; }
    }
}
