//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolaMundo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Drummond01Entities : DbContext
    {
        public Drummond01Entities()
            : base("name=Drummond01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaSubareas> AreaSubareas { get; set; }
        public virtual DbSet<CargosSet> CargosSet { get; set; }
        public virtual DbSet<DepartamentoAreaSet> DepartamentoAreaSet { get; set; }
        public virtual DbSet<DepartamentoSedeSet> DepartamentoSedeSet { get; set; }
        public virtual DbSet<departamentoSet> departamentoSet { get; set; }
        public virtual DbSet<EmpleadosSet> EmpleadosSet { get; set; }
        public virtual DbSet<GrupoAreas> GrupoAreas { get; set; }
        public virtual DbSet<GrupoSet> GrupoSet { get; set; }
        public virtual DbSet<SedeSet> SedeSet { get; set; }
        public virtual DbSet<SubareaSet> SubareaSet { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<AreasD> AreasD { get; set; }
    }
}
